version: "3"

services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      STORAGE_MODE : 'cached'
      MONGO_URL: 'mongodb://database:27017'
      MONGO_DBNAME: 'netwitter'
      REDIS_URL: 'cache:6379'

  database:
    image: mongo:4.4
    ports:
      - 27017:27017

  cache:
    image: redis:6.2.6
    ports:
      - 6739:6739
